#pragma once
#include <vector>
#include <string>
#include <sstream>
#include <cmath>

// ============================================================================
//  CloneCurve : a captured static transfer curve + its on-disk format.
//
//  The CLONE voicing is a *measured* input->output curve of a target unit,
//  played back through LutCloneStage (with ADAA). This struct is the contract
//  between the offline capture tool (tools/clone_capture.cpp) and the plugin:
//  N output samples for inputs spaced uniformly over [-range, +range].
//
//  Text format ("tekkcurve"), deliberately trivial so the JUCE-free DSP core
//  and the plugin can both read it with zero dependencies:
//
//      tekkcurve 1
//      range 4
//      n 2048
//      <y0>
//      <y1>
//      ...
//
//  '#' starts a comment to end-of-line; blank lines are ignored. An invalid
//  parse returns a CloneCurve with valid()==false (never throws).
// ============================================================================
struct CloneCurve
{
    float range = 1.0f;
    std::vector<float> samples;   // output for inputs uniform over [-range,+range]

    bool valid() const { return range > 0.0f && samples.size() >= 2; }

    std::string serialize() const
    {
        std::ostringstream os;
        os << "tekkcurve 1\n";
        os << "# captured static transfer curve for the TEKK Preamp clone path\n";
        os << "range " << range << "\n";
        os << "n " << samples.size() << "\n";
        os.setf (std::ios::fixed); os.precision (8);
        for (float v : samples) os << v << "\n";
        return os.str();
    }

    static CloneCurve parse (const std::string& text)
    {
        CloneCurve c; c.range = 0.0f;       // invalid until 'range' seen
        std::istringstream in (text);
        std::string line;
        bool gotMagic = false;
        long declaredN = -1;
        std::vector<float> vals;

        while (std::getline (in, line))
        {
            if (auto h = line.find ('#'); h != std::string::npos) line.erase (h);
            std::istringstream ls (line);
            std::string tok;
            if (! (ls >> tok)) continue;    // blank / comment-only

            if (! gotMagic)
            {
                if (tok != "tekkcurve") return {};
                gotMagic = true;            // (version token, if any, ignored)
                continue;
            }
            if (tok == "range")     { ls >> c.range; }
            else if (tok == "n")    { ls >> declaredN; }
            else                                            // a data value
            {
                try { vals.push_back (std::stof (tok)); }
                catch (...) { return {}; }
            }
        }
        (void) declaredN;                   // tolerated if it disagrees with size
        c.samples = std::move (vals);
        return c.valid() ? c : CloneCurve { 0.0f, {} };
    }

    // emit a C++ header embedding the curve (the baked-in default clone)
    std::string toCppHeader (const std::string& ns, const std::string& sym) const
    {
        std::ostringstream os;
        os << "#pragma once\n";
        os << "// GENERATED by tools/clone_capture.cpp -- do not edit by hand.\n";
        os << "// Captured static transfer curve for the TEKK Preamp clone path.\n\n";
        os << "namespace " << ns << " {\n";
        os.setf (std::ios::fixed); os.precision (8);
        os << "inline constexpr float " << sym << "Range = " << range << "f;\n";
        os << "inline constexpr int   " << sym << "N     = " << samples.size() << ";\n";
        os << "inline constexpr float " << sym << "[] = {\n";
        for (size_t i = 0; i < samples.size(); ++i)
        {
            os << (((i & 7) == 0) ? "    " : " ") << samples[i] << "f,";
            if ((i & 7) == 7) os << "\n";
        }
        if (samples.size() & 7) os << "\n";
        os << "};\n} // namespace " << ns << "\n";
        return os.str();
    }
};
